# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Travelgrunt < Formula
  desc "Travel Terragrunt directory tree as a first class passenger!"
  homepage "https://github.com/bmbferreira/travelgrunt"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.3/travelgrunt_0.0.3_darwin_amd64.tar.gz"
      sha256 "cc8da5f18d56416625a3673e2b651393b61363523d0252a3326e0f07b9be66e8"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.3/travelgrunt_0.0.3_darwin_arm64.tar.gz"
      sha256 "06377f4ce22a997a71eb14895396fa7f8b09463c76011543d8721e729b95f4d4"

      def install
        bin.install "travelgrunt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.3/travelgrunt_0.0.3_linux_arm64.tar.gz"
      sha256 "1435a926ffbc7aecb502bc89e9208f9f22169d4a6fd03ae4f3f96c1ed809e568"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.3/travelgrunt_0.0.3_linux_amd64.tar.gz"
      sha256 "3c2bfa5e50f0c448940c41098408b6c71cb716c8d5e71ce7a36bff31f354aa09"

      def install
        bin.install "travelgrunt"
      end
    end
  end
end
