# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Travelgrunt < Formula
  desc "Travel Terragrunt directory tree as a first class passenger!"
  homepage "https://github.com/bmbferreira/travelgrunt"
  version "0.0.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.11/travelgrunt_0.0.11_darwin_arm64.tar.gz"
      sha256 "1006a183d6bac1791d223bd1e6f1e7296bee199970a694aaaafc89d5906e5759"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.11/travelgrunt_0.0.11_darwin_amd64.tar.gz"
      sha256 "138cd122f0f6462b84812af7ebae58746c79f9db06b492eba646779c8d92cb62"

      def install
        bin.install "travelgrunt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.11/travelgrunt_0.0.11_linux_amd64.tar.gz"
      sha256 "c2cbf0212db672f812155ce23e80b26de17076e03ab0aed127ec7dc89f2ff48b"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bmbferreira/travelgrunt/releases/download/0.0.11/travelgrunt_0.0.11_linux_arm64.tar.gz"
      sha256 "001276979b8d2c51f752ee37ec559ef16b9ea546090c52c8d2c23c6534fb92f0"

      def install
        bin.install "travelgrunt"
      end
    end
  end
end
